Initial implementations of a Special Attack
DiddiLeija/diddi-and-the-bugs pull request #116
Opened 2023-03-25 10:10 UTC by HarshNarayanJha

This is the initial setup for our Special Attack!
This special attack will destroy all trash/enemies currently on screen. It will also cut the Monster’s health to half, if currently shown. To do this I needed to make the monster die after two hits, using a new variable on it called `hit_count`.

Right now the attack is triggered using the Z key (an attribute to the inspiration of this Easter egg, Z-move in Pokémon).

cc @DiddiLeija, as you already know, I can’t test this code. Please try this out and let me know!

Closes #115

2023-03-25 12:42 UTC, DiddiLeija commented
Great! I'll give it a look today :+1:

2023-03-25 12:50 UTC, DiddiLeija reviewed
Great start! Thank you @HarshNarayanJha. I haven't tested the behavior yet, but in terms of code sanity... here're a few suggestions ;)

2023-03-25 12:50 UTC, DiddiLeija commented on main.py
> +        self.hit_count += 1
Here's a whitespace, and seems like Flake8 is unhappy with that.

```suggestion

    def hit_special_move(self):
        self.hit_count += 1

```

2023-03-25 12:50 UTC, DiddiLeija commented on main.py
> +
Here, Flake8 proposes 2 faults: `multiple statements on one line (colon)`, which can be fixed easily in this case, and `too many blank lines (2)`. I propose this change:

```suggestion
        if pyxel.btnr(pyxel.KEY_Z):
            if self.used_special_move:
                return
            self.used_special_move = True
            # some cool animations
            for enem in self.enemies:
                if enem.is_alive and enem.show:
                    enem.hit_special_move()

            if self.monster.show and self.monster.alive:
                self.monster.hit_special_move()

```

2023-03-26 04:14 UTC, DiddiLeija requested changes
Ok, so... I tested the behavior. Pretty nice! Though it seems like trash is unaffected by the attack (was that intentional? maybe).

I just found a small typo, that was uncatched by linters :upside_down_face:

2023-03-26 04:14 UTC, DiddiLeija commented on main.py
> +                if enem.is_alive and enem.show:
It seems to me that `is_alive` was actually `alive`?

```suggestion
                if enem.alive and enem.show:
```

2023-03-26 08:00 UTC, HarshNarayanJha commented
> Though it seems like trash is unaffected by the attack (was that intentional? maybe).

No it wasn’t intentional.. as I forgot to iterate over trash list and kill them all 😅.. but I think it should be like that… only destroying enemies.

Now I only need to calculate the scores and add them… but what about animation and sound effect(s), we need something for it right?

2023-03-27 02:05 UTC, DiddiLeija commented
> No it wasn’t intentional.. as I forgot to iterate over trash list and kill them all 😅.. but I think it should be like that… only destroying enemies.

Yeah, since trash is a bonus item (not needed to win) :wink:

> but what about animation and sound effect(s), we need something for it right?

Yup. Maybe I can give it a look.

Or, you can design an animation/sound track using https://kitao.github.io/pyxel/wasm/examples/image_editor.html. Then you can download the content, send it to me, and I'll paste it in our resource file once we merge this PR?

2023-03-27 16:11 UTC, HarshNarayanJha commented
> Or, you can design an animation/sound track using

I really don’t know pixel art + I am currently learning animation (as you already know) and I really don’t know anything about music making. So sorry 😢

2023-03-27 19:55 UTC, DiddiLeija commented
> > Or, you can design an animation/sound track using
> 
> I really don’t know pixel art + I am currently learning animation (as you already know) and I really don’t know anything about music making. So sorry 😢

Ok, don't worry. Gonna try to do it myself, at least in the artistic part :)

2023-04-23 09:43 UTC, HarshNarayanJha commented
My implementations are done now. Opened for merging

2023-04-23 15:28 UTC, DiddiLeija approved these changes
It seems to be working, great job!
I'll try to get into graphics (and possibly docs) in the next days [^1]. ;)

[^1]: Oh, btw, maybe this PR should not close #115. I'll edit the first post in this thread :)

2023-04-23 15:30 UTC, merged